# Site settings
title: Boutique Wine Lady
email: christinaswyers@gmail.com
url: boutiquewinelady.com
description: "Boutique wine cellar and Distributor"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: BoutiqueWineLady.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://twitter.com/SBootstrap
  - title: instagram
    url: http://instagram.com
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
